# Generated by Django 3.2.21 on 2023-09-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_account',
            new_name='user_profile',
        ),
    ]
