# Generated by Django 3.2.21 on 2023-09-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Category',
        ),
    ]
