# Generated by Django 3.2.21 on 2023-09-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_producttype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
